In [2]:
import requests

In [2]:
flight_url = "https://raw.githubusercontent.com/Russell-sam/flight/refs/heads/main/flight.json"

In [ ]:
flight_content = requests.get(flight_url)

flight_content.status_code

200

In [ ]:

data = flight_content.json()

In [ ]:
type(data)

list

In [ ]:
data

[{'flight_number': 'LA2012',
  'airline_name': 'LATAM Airlines',
  'departure_airport': 'São Paulo/Guarulhos International',
  'departure_city': 'São Paulo',
  'departure_country': 'Brazil',
  'arrival_airport': 'Ministro Pistarini International',
  'arrival_city': 'Buenos Aires',
  'duration_hours': 1,
  'departure_time': '12/11/2022',
  'arrival_time': '7/23/2022'},
 {'flight_number': 'AC4413',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'Jomo Kenyatta International',
  'arrival_city': 'Nairobi',
  'duration_hours': 11,
  'departure_time': '11/2/2022',
  'arrival_time': '7/22/2022'},
 {'flight_number': 'SK1081',
  'airline_name': 'SAS Scandinavian',
  'departure_airport': 'Copenhagen Airport',
  'departure_city': 'Copenhagen',
  'departure_country': 'Denmark',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 13,
  'departure_time': '7/13/2022',
  'arrival_time': '12/25/2022'},
 {'flight_number': 'BA4091',
  'airline_name': 'British Airways',
  'departure_airport': 'Heathrow',
  'departure_city': 'London',
  'departure_country': 'UK',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 23,
  'departure_time': '8/8/2022',
  'arrival_time': '9/13/2022'},
 {'flight_number': 'TG9185',
  'airline_name': 'Thai Airways',
  'departure_airport': 'Suvarnabhumi',
  'departure_city': 'Bangkok',
  'departure_country': 'Thailand',
  'arrival_airport': 'Changi',
  'arrival_city': 'Singapore',
  'duration_hours': 7,
  'departure_time': '7/22/2022',
  'arrival_time': '1/22/2022'},
 {'flight_number': 'AC2255',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 10,
  'departure_time': '9/13/2022',
  'arrival_time': '4/8/2022'},
 {'flight_number': 'DL8764',
  'airline_name': 'Delta Air Lines',
  'departure_airport': 'John F. Kennedy International',
  'departure_city': 'New York',
  'departure_country': 'USA',
  'arrival_airport': 'Hartsfield-Jackson Atlanta',
  'arrival_city': 'Atlanta',
  'duration_hours': 8,
  'departure_time': '12/17/2022',
  'arrival_time': '8/10/2022'},
 {'flight_number': 'IB2561',
  'airline_name': 'Iberia',
  'departure_airport': 'Adolfo Suárez Madrid–Barajas',
  'departure_city': 'Madrid',
  'departure_country': 'Spain',
  'arrival_airport': 'Cairo International',
  'arrival_city': 'Cairo',
  'duration_hours': 4,
  'departure_time': '11/7/2022',
  'arrival_time': '3/13/2022'},
 {'flight_number': 'LH3478',
  'airline_name': 'Lufthansa',
  'departure_airport': 'Frankfurt Airport',
  'departure_city': 'Frankfurt',
  'departure_country': 'Germany',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 18,
  'departure_time': '1/3/2022',
  'arrival_time': '2/6/2022'},
 {'flight_number': 'SK6642',
  'airline_name': 'SAS Scandinavian',
  'departure_airport': 'Copenhagen Airport',
  'departure_city': 'Copenhagen',
  'departure_country': 'Denmark',
  'arrival_airport': 'Stockholm Arlanda',
  'arrival_city': 'Stockholm',
  'duration_hours': 16,
  'departure_time': '6/15/2022',
  'arrival_time': '12/9/2022'},
 {'flight_number': 'SK7338',
  'airline_name': 'SAS Scandinavian',
  'departure_airport': 'Copenhagen Airport',
  'departure_city': 'Copenhagen',
  'departure_country': 'Denmark',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 24,
  'departure_time': '9/30/2022',
  'arrival_time': '9/2/2022'},
 {'flight_number': 'AC9772',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 10,
  'departure_time': '6/20/2022',
  'arrival_time': '5/8/2022'},
 {'flight_number': 'KE3996',
  'airline_name': 'Korean Air',
  'departure_airport': 'Incheon International',
  'departure_city': 'Seoul',
  'departure_country': 'South Korea',
  'arrival_airport': 'Haneda',
  'arrival_city': 'Tokyo',
  'duration_hours': 13,
  'departure_time': '4/25/2022',
  'arrival_time': '3/6/2022'},
 {'flight_number': 'AC5567',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 24,
  'departure_time': '10/26/2022',
  'arrival_time': '8/29/2022'},
 {'flight_number': 'IB8620',
  'airline_name': 'Iberia',
  'departure_airport': 'Adolfo Suárez Madrid–Barajas',
  'departure_city': 'Madrid',
  'departure_country': 'Spain',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 5,
  'departure_time': '9/26/2022',
  'arrival_time': '9/15/2022'},
 {'flight_number': 'QR1765',
  'airline_name': 'Qatar Airways',
  'departure_airport': 'Hamad International',
  'departure_city': 'Doha',
  'departure_country': 'Qatar',
  'arrival_airport': 'Adolfo Suárez Madrid–Barajas',
  'arrival_city': 'Madrid',
  'duration_hours': 7,
  'departure_time': '6/2/2022',
  'arrival_time': '6/10/2022'},
 {'flight_number': 'SQ7261',
  'airline_name': 'Singapore Airlines',
  'departure_airport': 'Changi',
  'departure_city': 'Singapore',
  'departure_country': 'Singapore',
  'arrival_airport': 'Beijing Capital International',
  'arrival_city': 'Beijing',
  'duration_hours': 10,
  'departure_time': '1/25/2022',
  'arrival_time': '7/23/2022'},
 {'flight_number': 'LA4963',
  'airline_name': 'LATAM Airlines',
  'departure_airport': 'São Paulo/Guarulhos International',
  'departure_city': 'São Paulo',
  'departure_country': 'Brazil',
  'arrival_airport': 'Munich Airport',
  'arrival_city': 'Munich',
  'duration_hours': 14,
  'departure_time': '11/25/2022',
  'arrival_time': '6/15/2022'},
 {'flight_number': 'IB4174',
  'airline_name': 'Iberia',
  'departure_airport': 'Adolfo Suárez Madrid–Barajas',
  'departure_city': 'Madrid',
  'departure_country': 'Spain',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 7,
  'departure_time': '1/24/2022',
  'arrival_time': '5/25/2022'},
 {'flight_number': 'EK2269',
  'airline_name': 'Emirates',
  'departure_airport': 'Dubai International',
  'departure_city': 'Dubai',
  'departure_country': 'UAE',
  'arrival_airport': 'Hamad International',
  'arrival_city': 'Doha',
  'duration_hours': 21,
  'departure_time': '3/5/2022',
  'arrival_time': '11/15/2022'},
 {'flight_number': 'KL5768',
  'airline_name': 'KLM Royal Dutch Airlines',
  'departure_airport': 'Amsterdam Airport Schiphol',
  'departure_city': 'Amsterdam',
  'departure_country': 'Netherlands',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 8,
  'departure_time': '6/18/2022',
  'arrival_time': '8/11/2022'},
 {'flight_number': 'NZ9000',
  'airline_name': 'Air New Zealand',
  'departure_airport': 'Auckland Airport',
  'departure_city': 'Auckland',
  'departure_country': 'New Zealand',
  'arrival_airport': 'Munich Airport',
  'arrival_city': 'Munich',
  'duration_hours': 14,
  'departure_time': '9/27/2022',
  'arrival_time': '10/13/2022'},
 {'flight_number': 'SK4212',
  'airline_name': 'SAS Scandinavian',
  'departure_airport': 'Copenhagen Airport',
  'departure_city': 'Copenhagen',
  'departure_country': 'Denmark',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 6,
  'departure_time': '5/12/2022',
  'arrival_time': '7/8/2022'},
 {'flight_number': 'BA8026',
  'airline_name': 'British Airways',
  'departure_airport': 'Heathrow',
  'departure_city': 'London',
  'departure_country': 'UK',
  'arrival_airport': 'Vancouver International',
  'arrival_city': 'Vancouver',
  'duration_hours': 3,
  'departure_time': '3/28/2022',
  'arrival_time': '4/27/2022'},
 {'flight_number': 'AC8416',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 14,
  'departure_time': '8/16/2022',
  'arrival_time': '7/27/2022'},
 {'flight_number': 'IB3411',
  'airline_name': 'Iberia',
  'departure_airport': 'Adolfo Suárez Madrid–Barajas',
  'departure_city': 'Madrid',
  'departure_country': 'Spain',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 11,
  'departure_time': '11/4/2022',
  'arrival_time': '11/14/2022'},
 {'flight_number': 'LA9122',
  'airline_name': 'LATAM Airlines',
  'departure_airport': 'São Paulo/Guarulhos International',
  'departure_city': 'São Paulo',
  'departure_country': 'Brazil',
  'arrival_airport': 'Dallas/Fort Worth International',
  'arrival_city': 'Dallas',
  'duration_hours': 23,
  'departure_time': '10/7/2022',
  'arrival_time': '1/8/2022'},
 {'flight_number': 'WN4624',
  'airline_name': 'Southwest Airlines',
  'departure_airport': 'Los Angeles International',
  'departure_city': 'Los Angeles',
  'departure_country': 'USA',
  'arrival_airport': 'San Francisco International',
  'arrival_city': 'San Francisco',
  'duration_hours': 1,
  'departure_time': '12/1/2022',
  'arrival_time': '11/29/2022'},
 {'flight_number': 'QF6081',
  'airline_name': 'Qantas',
  'departure_airport': 'Sydney Airport',
  'departure_city': 'Sydney',
  'departure_country': 'Australia',
  'arrival_airport': 'Melbourne Airport',
  'arrival_city': 'Melbourne',
  'duration_hours': 6,
  'departure_time': '9/21/2022',
  'arrival_time': '11/26/2022'},
 {'flight_number': 'QF8880',
  'airline_name': 'Qantas',
  'departure_airport': 'Sydney Airport',
  'departure_city': 'Sydney',
  'departure_country': 'Australia',
  'arrival_airport': 'Melbourne Airport',
  'arrival_city': 'Melbourne',
  'duration_hours': 10,
  'departure_time': '7/11/2022',
  'arrival_time': '8/15/2022'},
 {'flight_number': 'KE6728',
  'airline_name': 'Korean Air',
  'departure_airport': 'Incheon International',
  'departure_city': 'Seoul',
  'departure_country': 'South Korea',
  'arrival_airport': 'Bole International',
  'arrival_city': 'Addis Ababa',
  'duration_hours': 1,
  'departure_time': '6/11/2022',
  'arrival_time': '4/26/2022'},
 {'flight_number': 'CX4515',
  'airline_name': 'Cathay Pacific',
  'departure_airport': 'Hong Kong International',
  'departure_city': 'Hong Kong',
  'departure_country': 'China',
  'arrival_airport': 'Changi',
  'arrival_city': 'Singapore',
  'duration_hours': 11,
  'departure_time': '11/7/2022',
  'arrival_time': '3/26/2022'},
 {'flight_number': 'AZ7920',
  'airline_name': 'Alitalia',
  'departure_airport': 'Leonardo da Vinci International',
  'departure_city': 'Rome',
  'departure_country': 'Italy',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 7,
  'departure_time': '9/25/2022',
  'arrival_time': '4/19/2022'},
 {'flight_number': 'AM8408',
  'airline_name': 'Aeroméxico',
  'departure_airport': 'Benito Juárez International',
  'departure_city': 'Mexico City',
  'departure_country': 'Mexico',
  'arrival_airport': 'Arturo Merino Benítez International',
  'arrival_city': 'Santiago',
  'duration_hours': 5,
  'departure_time': '5/19/2022',
  'arrival_time': '9/8/2022'},
 {'flight_number': 'IB2413',
  'airline_name': 'Iberia',
  'departure_airport': 'Adolfo Suárez Madrid–Barajas',
  'departure_city': 'Madrid',
  'departure_country': 'Spain',
  'arrival_airport': 'Cape Town International',
  'arrival_city': 'Cape Town',
  'duration_hours': 9,
  'departure_time': '9/21/2022',
  'arrival_time': '3/16/2022'},
 {'flight_number': 'ET1556',
  'airline_name': 'Ethiopian Airlines',
  'departure_airport': 'Bole International',
  'departure_city': 'Addis Ababa',
  'departure_country': 'Ethiopia',
  'arrival_airport': 'Adolfo Suárez Madrid–Barajas',
  'arrival_city': 'Madrid',
  'duration_hours': 11,
  'departure_time': '3/3/2022',
  'arrival_time': '1/24/2022'},
 {'flight_number': 'LH4362',
  'airline_name': 'Lufthansa',
  'departure_airport': 'Frankfurt Airport',
  'departure_city': 'Frankfurt',
  'departure_country': 'Germany',
  'arrival_airport': 'São Paulo/Guarulhos International',
  'arrival_city': 'São Paulo',
  'duration_hours': 19,
  'departure_time': '12/27/2022',
  'arrival_time': '1/13/2022'},
 {'flight_number': 'BA5838',
  'airline_name': 'British Airways',
  'departure_airport': 'Heathrow',
  'departure_city': 'London',
  'departure_country': 'UK',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 15,
  'departure_time': '10/5/2022',
  'arrival_time': '8/1/2022'},
 {'flight_number': 'AC4205',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 16,
  'departure_time': '3/3/2022',
  'arrival_time': '10/3/2022'},
 {'flight_number': 'NZ1348',
  'airline_name': 'Air New Zealand',
  'departure_airport': 'Auckland Airport',
  'departure_city': 'Auckland',
  'departure_country': 'New Zealand',
  'arrival_airport': 'Sydney Airport',
  'arrival_city': 'Sydney',
  'duration_hours': 2,
  'departure_time': '5/21/2022',
  'arrival_time': '3/23/2022'},
 {'flight_number': 'SK4478',
  'airline_name': 'SAS Scandinavian',
  'departure_airport': 'Copenhagen Airport',
  'departure_city': 'Copenhagen',
  'departure_country': 'Denmark',
  'arrival_airport': 'Heathrow',
  'arrival_city': 'London',
  'duration_hours': 20,
  'departure_time': '1/7/2022',
  'arrival_time': '10/21/2022'},
 {'flight_number': 'AF9202',
  'airline_name': 'Air France',
  'departure_airport': 'Charles de Gaulle',
  'departure_city': 'Paris',
  'departure_country': 'France',
  'arrival_airport': 'Frankfurt Airport',
  'arrival_city': 'Frankfurt',
  'duration_hours': 20,
  'departure_time': '1/16/2022',
  'arrival_time': '7/12/2022'},
 {'flight_number': 'TG4099',
  'airline_name': 'Thai Airways',
  'departure_airport': 'Suvarnabhumi',
  'departure_city': 'Bangkok',
  'departure_country': 'Thailand',
  'arrival_airport': 'Brisbane Airport',
  'arrival_city': 'Brisbane',
  'duration_hours': 5,
  'departure_time': '12/29/2022',
  'arrival_time': '7/23/2022'},
 {'flight_number': 'WN5978',
  'airline_name': 'Southwest Airlines',
  'departure_airport': 'Los Angeles International',
  'departure_city': 'Los Angeles',
  'departure_country': 'USA',
  'arrival_airport': 'Vancouver International',
  'arrival_city': 'Vancouver',
  'duration_hours': 19,
  'departure_time': '9/15/2022',
  'arrival_time': '3/31/2022'},
 {'flight_number': 'AC6923',
  'airline_name': 'Air Canada',
  'departure_airport': 'Toronto Pearson',
  'departure_city': 'Toronto',
  'departure_country': 'Canada',
  'arrival_airport': 'John F. Kennedy International',
  'arrival_city': 'New York',
  'duration_hours': 10,
  'departure_time': '9/23/2022',
  'arrival_time': '10/12/2022'},
 {'flight_number': 'KL6466',
  'airline_name': 'KLM Royal Dutch Airlines',
  'departure_airport': 'Amsterdam Airport Schiphol',
  'departure_city': 'Amsterdam',
  'departure_country': 'Netherlands',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 1,
  'departure_time': '5/31/2022',
  'arrival_time': '2/23/2022'},
 {'flight_number': 'AI9055',
  'airline_name': 'Air India',
  'departure_airport': 'Indira Gandhi International',
  'departure_city': 'Delhi',
  'departure_country': 'India',
  'arrival_airport': 'Chhatrapati Shivaji International',
  'arrival_city': 'Mumbai',
  'duration_hours': 5,
  'departure_time': '7/22/2022',
  'arrival_time': '9/27/2022'},
 {'flight_number': 'AZ1940',
  'airline_name': 'Alitalia',
  'departure_airport': 'Leonardo da Vinci International',
  'departure_city': 'Rome',
  'departure_country': 'Italy',
  'arrival_airport': 'Charles de Gaulle',
  'arrival_city': 'Paris',
  'duration_hours': 15,
  'departure_time': '11/11/2022',
  'arrival_time': '3/24/2022'},
 {'flight_number': 'CX4309',
  'airline_name': 'Cathay Pacific',
  'departure_airport': 'Hong Kong International',
  'departure_city': 'Hong Kong',
  'departure_country': 'China',
  'arrival_airport': 'Adolfo Suárez Madrid–Barajas',
  'arrival_city': 'Madrid',
  'duration_hours': 5,
  'departure_time': '8/8/2022',
  'arrival_time': '3/3/2022'},
 {'flight_number': 'LA7443',
  'airline_name': 'LATAM Airlines',
  'departure_airport': 'São Paulo/Guarulhos International',
  'departure_city': 'São Paulo',
  'departure_country': 'Brazil',
  'arrival_airport': 'Los Angeles International',
  'arrival_city': 'Los Angeles',
  'duration_hours': 13,
  'departure_time': '10/1/2022',
  'arrival_time': '2/7/2022'}]

In [ ]:
import pandas

In [ ]:
flight_df = pandas.DataFrame(data)
flight_df

,flight_number,airline_name,departure_airport,departure_city,departure_country,arrival_airport,arrival_city,duration_hours,departure_time,arrival_time
0,LA2012,LATAM Airlines,São Paulo/Guarulhos International,São Paulo,Brazil,Ministro Pistarini International,Buenos Aires,1,12/11/2022,7/23/2022
1,AC4413,Air Canada,Toronto Pearson,Toronto,Canada,Jomo Kenyatta International,Nairobi,11,11/2/2022,7/22/2022
2,SK1081,SAS Scandinavian,Copenhagen Airport,Copenhagen,Denmark,Charles de Gaulle,Paris,13,7/13/2022,12/25/2022
3,BA4091,British Airways,Heathrow,London,UK,Charles de Gaulle,Paris,23,8/8/2022,9/13/2022
4,TG9185,Thai Airways,Suvarnabhumi,Bangkok,Thailand,Changi,Singapore,7,7/22/2022,1/22/2022
5,AC2255,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,10,9/13/2022,4/8/2022
6,DL8764,Delta Air Lines,John F. Kennedy International,New York,USA,Hartsfield-Jackson Atlanta,Atlanta,8,12/17/2022,8/10/2022
7,IB2561,Iberia,Adolfo Suárez Madrid–Barajas,Madrid,Spain,Cairo International,Cairo,4,11/7/2022,3/13/2022
8,LH3478,Lufthansa,Frankfurt Airport,Frankfurt,Germany,Charles de Gaulle,Paris,18,1/3/2022,2/6/2022
9,SK6642,SAS Scandinavian,Copenhagen Airport,Copenhagen,Denmark,Stockholm Arlanda,Stockholm,16,6/15/2022,12/9/2022
10,SK7338,SAS Scandinavian,Copenhagen Airport,Copenhagen,Denmark,Charles de Gaulle,Paris,24,9/30/2022,9/2/2022
11,AC9772,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,10,6/20/2022,5/8/2022
12,KE3996,Korean Air,Incheon International,Seoul,South Korea,Haneda,Tokyo,13,4/25/2022,3/6/2022
13,AC5567,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,24,10/26/2022,8/29/2022
14,IB8620,Iberia,Adolfo Suárez Madrid–Barajas,Madrid,Spain,Charles de Gaulle,Paris,5,9/26/2022,9/15/2022
15,QR1765,Qatar Airways,Hamad International,Doha,Qatar,Adolfo Suárez Madrid–Barajas,Madrid,7,6/2/2022,6/10/2022
16,SQ7261,Singapore Airlines,Changi,Singapore,Singapore,Beijing Capital International,Beijing,10,1/25/2022,7/23/2022
17,LA4963,LATAM Airlines,São Paulo/Guarulhos International,São Paulo,Brazil,Munich Airport,Munich,14,11/25/2022,6/15/2022
18,IB4174,Iberia,Adolfo Suárez Madrid–Barajas,Madrid,Spain,Charles de Gaulle,Paris,7,1/24/2022,5/25/2022
19,EK2269,Emirates,Dubai International,Dubai,UAE,Hamad International,Doha,21,3/5/2022,11/15/2022
20,KL5768,KLM Royal Dutch Airlines,Amsterdam Airport Schiphol,Amsterdam,Netherlands,Charles de Gaulle,Paris,8,6/18/2022,8/11/2022
21,NZ9000,Air New Zealand,Auckland Airport,Auckland,New Zealand,Munich Airport,Munich,14,9/27/2022,10/13/2022
22,SK4212,SAS Scandinavian,Copenhagen Airport,Copenhagen,Denmark,Charles de Gaulle,Paris,6,5/12/2022,7/8/2022
23,BA8026,British Airways,Heathrow,London,UK,Vancouver International,Vancouver,3,3/28/2022,4/27/2022
24,AC8416,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,14,8/16/2022,7/27/2022
25,IB3411,Iberia,Adolfo Suárez Madrid–Barajas,Madrid,Spain,Charles de Gaulle,Paris,11,11/4/2022,11/14/2022
26,LA9122,LATAM Airlines,São Paulo/Guarulhos International,São Paulo,Brazil,Dallas/Fort Worth International,Dallas,23,10/7/2022,1/8/2022
27,WN4624,Southwest Airlines,Los Angeles International,Los Angeles,USA,San Francisco International,San Francisco,1,12/1/2022,11/29/2022
28,QF6081,Qantas,Sydney Airport,Sydney,Australia,Melbourne Airport,Melbourne,6,9/21/2022,11/26/2022
29,QF8880,Qantas,Sydney Airport,Sydney,Australia,Melbourne Airport,Melbourne,10,7/11/2022,8/15/2022
30,KE6728,Korean Air,Incheon International,Seoul,South Korea,Bole International,Addis Ababa,1,6/11/2022,4/26/2022
31,CX4515,Cathay Pacific,Hong Kong International,Hong Kong,China,Changi,Singapore,11,11/7/2022,3/26/2022
32,AZ7920,Alitalia,Leonardo da Vinci International,Rome,Italy,Charles de Gaulle,Paris,7,9/25/2022,4/19/2022
33,AM8408,Aeroméxico,Benito Juárez International,Mexico City,Mexico,Arturo Merino Benítez International,Santiago,5,5/19/2022,9/8/2022
34,IB2413,Iberia,Adolfo Suárez Madrid–Barajas,Madrid,Spain,Cape Town International,Cape Town,9,9/21/2022,3/16/2022
35,ET1556,Ethiopian Airlines,Bole International,Addis Ababa,Ethiopia,Adolfo Suárez Madrid–Barajas,Madrid,11,3/3/2022,1/24/2022
36,LH4362,Lufthansa,Frankfurt Airport,Frankfurt,Germany,São Paulo/Guarulhos International,São Paulo,19,12/27/2022,1/13/2022
37,BA5838,British Airways,Heathrow,London,UK,Charles de Gaulle,Paris,15,10/5/2022,8/1/2022
38,AC4205,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,16,3/3/2022,10/3/2022
39,NZ1348,Air New Zealand,Auckland Airport,Auckland,New Zealand,Sydney Airport,Sydney,2,5/21/2022,3/23/2022
40,SK4478,SAS Scandinavian,Copenhagen Airport,Copenhagen,Denmark,Heathrow,London,20,1/7/2022,10/21/2022
41,AF9202,Air France,Charles de Gaulle,Paris,France,Frankfurt Airport,Frankfurt,20,1/16/2022,7/12/2022
42,TG4099,Thai Airways,Suvarnabhumi,Bangkok,Thailand,Brisbane Airport,Brisbane,5,12/29/2022,7/23/2022
43,WN5978,Southwest Airlines,Los Angeles International,Los Angeles,USA,Vancouver International,Vancouver,19,9/15/2022,3/31/2022
44,AC6923,Air Canada,Toronto Pearson,Toronto,Canada,John F. Kennedy International,New York,10,9/23/2022,10/12/2022
45,KL6466,KLM Royal Dutch Airlines,Amsterdam Airport Schiphol,Amsterdam,Netherlands,Charles de Gaulle,Paris,1,5/31/2022,2/23/2022
46,AI9055,Air India,Indira Gandhi International,Delhi,India,Chhatrapati Shivaji International,Mumbai,5,7/22/2022,9/27/2022
47,AZ1940,Alitalia,Leonardo da Vinci International,Rome,Italy,Charles de Gaulle,Paris,15,11/11/2022,3/24/2022
48,CX4309,Cathay Pacific,Hong Kong International,Hong Kong,China,Adolfo Suárez Madrid–Barajas,Madrid,5,8/8/2022,3/3/2022
49,LA7443,LATAM Airlines,São Paulo/Guarulhos International,São Paulo,Brazil,Los Angeles International,Los Angeles,13,10/1/2022,2/7/2022

In [ ]:
flight_df.to_csv("flight_data.csv")

### Part 3: Working with DummyJSON API Endpoints

In [3]:

response = requests.get("https://dummyjson.com/products")

In [4]:
response.status_code

200

In [6]:
products = response.json()

In [7]:
type(products)

dict

In [8]:
products

{'products': [{'id': 1,
   'title': 'Essence Mascara Lash Princess',
   'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
   'category': 'beauty',
   'price': 9.99,
   'discountPercentage': 10.48,
   'rating': 2.56,
   'stock': 99,
   'tags': ['beauty', 'mascara'],
   'brand': 'Essence',
   'sku': 'BEA-ESS-ESS-001',
   'weight': 4,
   'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 3-5 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 3,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Very satisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Lucas Gordon',
     'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Eleanor Collins',
     'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 48,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '5784719087687',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
  {'id': 2,
   'title': 'Eyeshadow Palette with Mirror',
   'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
   'category': 'beauty',
   'price': 19.99,
   'discountPercentage': 18.19,
   'rating': 2.86,
   'stock': 34,
   'tags': ['beauty', 'eyeshadow'],
   'brand': 'Glamour Beauty',
   'sku': 'BEA-GLA-EYE-002',
   'weight': 9,
   'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Savannah Gomez',
     'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christian Perez',
     'reviewerEmail': 'christian.perez@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 20,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9170275171413',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
  {'id': 3,
   'title': 'Powder Canister',
   'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
   'category': 'beauty',
   'price': 14.99,
   'discountPercentage': 9.84,
   'rating': 4.64,
   'stock': 89,
   'tags': ['beauty', 'face powder'],
   'brand': 'Velvet Touch',
   'sku': 'BEA-VEL-POW-003',
   'weight': 8,
   'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
   'warrantyInformation': '3 months warranty',
   'shippingInformation': 'Ships in 1-2 business days',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Alexander Jones',
     'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Elijah Cruz',
     'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Avery Perez',
     'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '8418883906837',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
  {'id': 4,
   'title': 'Red Lipstick',
   'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
   'category': 'beauty',
   'price': 12.99,
   'discountPercentage': 12.16,
   'rating': 4.36,
   'stock': 91,
   'tags': ['beauty', 'lipstick'],
   'brand': 'Chic Cosmetics',
   'sku': 'BEA-CHI-LIP-004',
   'weight': 1,
   'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 week',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Garcia',
     'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 40,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '9467746727219',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
  {'id': 5,
   'title': 'Red Nail Polish',
   'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
   'category': 'beauty',
   'price': 8.99,
   'discountPercentage': 11.44,
   'rating': 4.32,
   'stock': 79,
   'tags': ['beauty', 'nail polish'],
   'brand': 'Nail Couture',
   'sku': 'BEA-NAI-NAI-005',
   'weight': 8,
   'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
   'warrantyInformation': '1 month warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Benjamin Wilson',
     'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Liam Smith',
     'reviewerEmail': 'liam.smith@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Very unhappy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Clara Berry',
     'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 22,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4063010628104',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'},
  {'id': 6,
   'title': 'Calvin Klein CK One',
   'description': "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
   'category': 'fragrances',
   'price': 49.99,
   'discountPercentage': 1.89,
   'rating': 4.37,
   'stock': 29,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Calvin Klein',
   'sku': 'FRA-CAL-CAL-006',
   'weight': 7,
   'dimensions': {'width': 29.36, 'height': 27.76, 'depth': 20.72},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Very disappointed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Layla Young',
     'reviewerEmail': 'layla.young@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Fast shipping!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 3,
     'comment': 'Not as described!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Jacob Cooper',
     'reviewerEmail': 'jacob.cooper@x.dummyjson.com'}],
   'returnPolicy': '90 days return policy',
   'minimumOrderQuantity': 9,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '2451534060749',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp'},
  {'id': 7,
   'title': 'Chanel Coco Noir Eau De',
   'description': 'Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.',
   'category': 'fragrances',
   'price': 129.99,
   'discountPercentage': 16.51,
   'rating': 4.26,
   'stock': 58,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Chanel',
   'sku': 'FRA-CHA-CHA-007',
   'weight': 7,
   'dimensions': {'width': 24.5, 'height': 25.7, 'depth': 25.98},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Ruby Andrews',
     'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Awesome product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Leah Henderson',
     'reviewerEmail': 'leah.henderson@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Xavier Wright',
     'reviewerEmail': 'xavier.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '4091737746820',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp'},
  {'id': 8,
   'title': "Dior J'adore",
   'description': "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
   'category': 'fragrances',
   'price': 89.99,
   'discountPercentage': 14.72,
   'rating': 3.8,
   'stock': 98,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dior',
   'sku': 'FRA-DIO-DIO-008',
   'weight': 4,
   'dimensions': {'width': 27.67, 'height': 28.28, 'depth': 11.83},
   'warrantyInformation': '1 week warranty',
   'shippingInformation': 'Ships in 2 weeks',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 5,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nicholas Bailey',
     'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great value for money!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Penelope Harper',
     'reviewerEmail': 'penelope.harper@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Great product!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Emma Miller',
     'reviewerEmail': 'emma.miller@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 10,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '1445086097250',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ["https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp"],
   'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
  {'id': 9,
   'title': 'Dolce Shine Eau de',
   'description': "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
   'category': 'fragrances',
   'price': 69.99,
   'discountPercentage': 0.62,
   'rating': 3.96,
   'stock': 4,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Dolce & Gabbana',
   'sku': 'FRA-DOL-DOL-009',
   'weight': 6,
   'dimensions': {'width': 27.28, 'height': 29.88, 'depth': 18.3},
   'warrantyInformation': '3 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'Low Stock',
   'reviews': [{'rating': 4,
     'comment': 'Would buy again!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mateo Bennett',
     'reviewerEmail': 'mateo.bennett@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly recommended!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Nolan Gonzalez',
     'reviewerEmail': 'nolan.gonzalez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Aurora Lawson',
     'reviewerEmail': 'aurora.lawson@x.dummyjson.com'}],
   'returnPolicy': '7 days return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3023868210708',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp'},
  {'id': 10,
   'title': 'Gucci Bloom Eau de',
   'description': "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
   'category': 'fragrances',
   'price': 79.99,
   'discountPercentage': 14.39,
   'rating': 2.74,
   'stock': 91,
   'tags': ['fragrances', 'perfumes'],
   'brand': 'Gucci',
   'sku': 'FRA-GUC-GUC-010',
   'weight': 7,
   'dimensions': {'width': 20.92, 'height': 21.68, 'depth': 11.2},
   'warrantyInformation': '6 months warranty',
   'shippingInformation': 'Ships overnight',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 1,
     'comment': 'Very dissatisfied!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Cameron Perez',
     'reviewerEmail': 'cameron.perez@x.dummyjson.com'},
    {'rating': 5,
     'comment': 'Very happy with my purchase!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Daniel Cook',
     'reviewerEmail': 'daniel.cook@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Addison Wright',
     'reviewerEmail': 'addison.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 2,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3170832177880',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp',
    'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp'},
  {'id': 11,
   'title': 'Annibale Colombo Bed',
   'description': 'The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.',
   'category': 'furniture',
   'price': 1899.99,
   'discountPercentage': 8.57,
   'rating': 4.77,
   'stock': 88,
   'tags': ['furniture', 'beds'],
   'brand': 'Annibale Colombo',
   'sku': 'FUR-ANN-ANN-011',
   'weight': 10,
   'dimensions': {'width': 28.16, 'height': 25.36, 'depth': 17.28},
   'warrantyInformation': '1 year warranty',
   'shippingInformation': 'Ships in 1 month',
   'availabilityStatus': 'In Stock',
   'reviews': [{'rating': 2,
     'comment': 'Would not recommend!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Christopher West',
     'reviewerEmail': 'christopher.west@x.dummyjson.com'},
    {'rating': 4,
     'comment': 'Highly impressed!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Vivian Carter',
     'reviewerEmail': 'vivian.carter@x.dummyjson.com'},
    {'rating': 1,
     'comment': 'Poor quality!',
     'date': '2025-04-30T09:41:02.053Z',
     'reviewerName': 'Mason Wright',
     'reviewerEmail': 'mason.wright@x.dummyjson.com'}],
   'returnPolicy': 'No return policy',
   'minimumOrderQuantity': 1,
   'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
    'updatedAt': '2025-04-30T09:41:02.053Z',
    'barcode': '3610757456581',
    'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
   'images': ['https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/1.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/2.webp',
    'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/3.webp'],
   'thumbnail': 'https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp'},
  {'id': 12,
   'title': 'Annibale Colombo Sofa',
   'description': 'The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.',
   'category': 'furniture',
   'price': 2499.99,
   'discountPercentage': 14.4,

In [9]:
products.keys()

dict_keys(['products', 'total', 'skip', 'limit'])

In [10]:
products['products'][:5]

[{'id': 1,
  'title': 'Essence Mascara Lash Princess',
  'description': 'The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.',
  'category': 'beauty',
  'price': 9.99,
  'discountPercentage': 10.48,
  'rating': 2.56,
  'stock': 99,
  'tags': ['beauty', 'mascara'],
  'brand': 'Essence',
  'sku': 'BEA-ESS-ESS-001',
  'weight': 4,
  'dimensions': {'width': 15.14, 'height': 13.08, 'depth': 22.99},
  'warrantyInformation': '1 week warranty',
  'shippingInformation': 'Ships in 3-5 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 3,
    'comment': 'Would not recommend!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Very satisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Lucas Gordon',
    'reviewerEmail': 'lucas.gordon@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Eleanor Collins',
    'reviewerEmail': 'eleanor.collins@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 48,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '5784719087687',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp'},
 {'id': 2,
  'title': 'Eyeshadow Palette with Mirror',
  'description': "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
  'category': 'beauty',
  'price': 19.99,
  'discountPercentage': 18.19,
  'rating': 2.86,
  'stock': 34,
  'tags': ['beauty', 'eyeshadow'],
  'brand': 'Glamour Beauty',
  'sku': 'BEA-GLA-EYE-002',
  'weight': 9,
  'dimensions': {'width': 9.26, 'height': 22.47, 'depth': 27.67},
  'warrantyInformation': '1 year warranty',
  'shippingInformation': 'Ships in 2 weeks',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Savannah Gomez',
    'reviewerEmail': 'savannah.gomez@x.dummyjson.com'},
   {'rating': 4,
    'comment': 'Awesome product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Christian Perez',
    'reviewerEmail': 'christian.perez@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Nicholas Bailey',
    'reviewerEmail': 'nicholas.bailey@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 20,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9170275171413',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp'},
 {'id': 3,
  'title': 'Powder Canister',
  'description': 'The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.',
  'category': 'beauty',
  'price': 14.99,
  'discountPercentage': 9.84,
  'rating': 4.64,
  'stock': 89,
  'tags': ['beauty', 'face powder'],
  'brand': 'Velvet Touch',
  'sku': 'BEA-VEL-POW-003',
  'weight': 8,
  'dimensions': {'width': 29.27, 'height': 27.93, 'depth': 20.59},
  'warrantyInformation': '3 months warranty',
  'shippingInformation': 'Ships in 1-2 business days',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Alexander Jones',
    'reviewerEmail': 'alexander.jones@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Highly impressed!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Elijah Cruz',
    'reviewerEmail': 'elijah.cruz@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very dissatisfied!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Avery Perez',
    'reviewerEmail': 'avery.perez@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '8418883906837',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp'},
 {'id': 4,
  'title': 'Red Lipstick',
  'description': 'The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.',
  'category': 'beauty',
  'price': 12.99,
  'discountPercentage': 12.16,
  'rating': 4.36,
  'stock': 91,
  'tags': ['beauty', 'lipstick'],
  'brand': 'Chic Cosmetics',
  'sku': 'BEA-CHI-LIP-004',
  'weight': 1,
  'dimensions': {'width': 18.11, 'height': 28.38, 'depth': 22.17},
  'warrantyInformation': '3 year warranty',
  'shippingInformation': 'Ships in 1 week',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 4,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Garcia',
    'reviewerEmail': 'liam.garcia@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Ruby Andrews',
    'reviewerEmail': 'ruby.andrews@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Would buy again!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': '7 days return policy',
  'minimumOrderQuantity': 40,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '9467746727219',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp'},
 {'id': 5,
  'title': 'Red Nail Polish',
  'description': 'The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.',
  'category': 'beauty',
  'price': 8.99,
  'discountPercentage': 11.44,
  'rating': 4.32,
  'stock': 79,
  'tags': ['beauty', 'nail polish'],
  'brand': 'Nail Couture',
  'sku': 'BEA-NAI-NAI-005',
  'weight': 8,
  'dimensions': {'width': 21.63, 'height': 16.48, 'depth': 29.84},
  'warrantyInformation': '1 month warranty',
  'shippingInformation': 'Ships overnight',
  'availabilityStatus': 'In Stock',
  'reviews': [{'rating': 2,
    'comment': 'Poor quality!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Benjamin Wilson',
    'reviewerEmail': 'benjamin.wilson@x.dummyjson.com'},
   {'rating': 5,
    'comment': 'Great product!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Liam Smith',
    'reviewerEmail': 'liam.smith@x.dummyjson.com'},
   {'rating': 1,
    'comment': 'Very unhappy with my purchase!',
    'date': '2025-04-30T09:41:02.053Z',
    'reviewerName': 'Clara Berry',
    'reviewerEmail': 'clara.berry@x.dummyjson.com'}],
  'returnPolicy': 'No return policy',
  'minimumOrderQuantity': 22,
  'meta': {'createdAt': '2025-04-30T09:41:02.053Z',
   'updatedAt': '2025-04-30T09:41:02.053Z',
   'barcode': '4063010628104',
   'qrCode': 'https://cdn.dummyjson.com/public/qr-code.png'},
  'images': ['https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp'],
  'thumbnail': 'https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp'}]

In [11]:
products = products['products']

In [13]:
import pandas as pd

In [14]:
products_df = pd.json_normalize(products)
products_df.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
2,3,Powder Canister,The Powder Canister is a finely milled setting...,beauty,14.99,9.84,4.64,89,"[beauty, face powder]",Velvet Touch,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,29.27,27.93,20.59,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,8418883906837,https://cdn.dummyjson.com/public/qr-code.png
3,4,Red Lipstick,The Red Lipstick is a classic and bold choice ...,beauty,12.99,12.16,4.36,91,"[beauty, lipstick]",Chic Cosmetics,...,40,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,18.11,28.38,22.17,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9467746727219,https://cdn.dummyjson.com/public/qr-code.png
4,5,Red Nail Polish,The Red Nail Polish offers a rich and glossy r...,beauty,8.99,11.44,4.32,79,"[beauty, nail polish]",Nail Couture,...,22,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,21.63,16.48,29.84,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,4063010628104,https://cdn.dummyjson.com/public/qr-code.png

In [15]:
products_exploded = products_df.explode('reviews').reset_index(drop=True)
products_exploded.head()

,id,title,description,category,price,discountPercentage,rating,stock,tags,brand,...,minimumOrderQuantity,images,thumbnail,dimensions.width,dimensions.height,dimensions.depth,meta.createdAt,meta.updatedAt,meta.barcode,meta.qrCode
0,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
1,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
2,1,Essence Mascara Lash Princess,The Essence Mascara Lash Princess is a popular...,beauty,9.99,10.48,2.56,99,"[beauty, mascara]",Essence,...,48,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,15.14,13.08,22.99,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,5784719087687,https://cdn.dummyjson.com/public/qr-code.png
3,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png
4,2,Eyeshadow Palette with Mirror,The Eyeshadow Palette with Mirror offers a ver...,beauty,19.99,18.19,2.86,34,"[beauty, eyeshadow]",Glamour Beauty,...,20,[https://cdn.dummyjson.com/product-images/beau...,https://cdn.dummyjson.com/product-images/beaut...,9.26,22.47,27.67,2025-04-30T09:41:02.053Z,2025-04-30T09:41:02.053Z,9170275171413,https://cdn.dummyjson.com/public/qr-code.png

In [16]:
print(products_exploded.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    90 non-null     int64
 1   title                 90 non-null     object
 2   description           90 non-null     object
 3   category              90 non-null     object
 4   price                 90 non-null     float64
 5   discountPercentage    90 non-null     float64
 6   rating                90 non-null     float64
 7   stock                 90 non-null     int64
 8   tags                  90 non-null     object
 9   brand                 45 non-null     object
 10  sku                   90 non-null     object
 11  weight                90 non-null     int64
 12  warrantyInformation   90 non-null     object
 13  shippingInformation   90 non-null     object
 14  availabilityStatus    90 non-null     object
 15  reviews               90 non-null     object
 16  returnPolicy          90 non-null     object
 17  minimumOrderQuantity  90 non-null     int64
 18  images                90 non-null     object
 19  thumbnail             90 non-null     object
 20  dimensions.width      90 non-null     float64
 21  dimensions.height     90 non-null     float64
 22  dimensions.depth      90 non-null     float64
 23  meta.createdAt        90 non-null     object
 24  meta.updatedAt        90 non-null     object
 25  meta.barcode          90 non-null     object
 26  meta.qrCode           90 non-null     object
dtypes: float64(6), int64(4), object(17)
memory usage: 19.1+ KB
None

In [17]:
if not products_exploded['reviews'].isna().all():
    reviews_products = pd.json_normalize(products_exploded['reviews'])

    # Add a prefix so you know these columns belong to the review
    reviews_products = reviews_products.add_prefix('review_')

    # Join the exploded product data with the flattened review data(drop old review column)
    products_final = pd.concat([products_exploded.drop(columns=['reviews']), reviews_products], axis=1)
else:
    # If no reviews existed at all
    products_final = products_exploded.drop(columns=['reviews'])

In [18]:
products_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 31 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    90 non-null     int64
 1   title                 90 non-null     object
 2   description           90 non-null     object
 3   category              90 non-null     object
 4   price                 90 non-null     float64
 5   discountPercentage    90 non-null     float64
 6   rating                90 non-null     float64
 7   stock                 90 non-null     int64
 8   tags                  90 non-null     object
 9   brand                 45 non-null     object
 10  sku                   90 non-null     object
 11  weight                90 non-null     int64
 12  warrantyInformation   90 non-null     object
 13  shippingInformation   90 non-null     object
 14  availabilityStatus    90 non-null     object
 15  returnPolicy          90 non-null     object
 16  minimumOrderQuantity  90 non-null     int64
 17  images                90 non-null     object
 18  thumbnail             90 non-null     object
 19  dimensions.width      90 non-null     float64
 20  dimensions.height     90 non-null     float64
 21  dimensions.depth      90 non-null     float64
 22  meta.createdAt        90 non-null     object
 23  meta.updatedAt        90 non-null     object
 24  meta.barcode          90 non-null     object
 25  meta.qrCode           90 non-null     object
 26  review_rating         90 non-null     int64
 27  review_comment        90 non-null     object
 28  review_date           90 non-null     object
 29  review_reviewerName   90 non-null     object
 30  review_reviewerEmail  90 non-null     object
dtypes: float64(6), int64(5), object(20)
memory usage: 21.9+ KB

In [19]:
products_final.to_csv('products.csv', index=False)

In [20]:
# carts
carts_url= "https://dummyjson.com/carts"

res = requests.get(carts_url)
res.status_code

200

In [21]:
carts = res.json()
type(carts)

dict

In [22]:
carts.keys()

dict_keys(['carts', 'total', 'skip', 'limit'])

In [23]:
carts['carts'][:4]

[{'id': 1,
  'products': [{'id': 162,
    'title': 'Blue Frock',
    'price': 29.99,
    'quantity': 4,
    'total': 119.96,
    'discountPercentage': 12.13,
    'discountedTotal': 105.41,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp'},
   {'id': 113,
    'title': 'Generic Motorcycle',
    'price': 3999.99,
    'quantity': 3,
    'total': 11999.97,
    'discountPercentage': 12.1,
    'discountedTotal': 10547.97,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp'},
   {'id': 122,
    'title': 'iPhone 6',
    'price': 299.99,
    'quantity': 3,
    'total': 899.97,
    'discountPercentage': 6.69,
    'discountedTotal': 839.76,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp'},
   {'id': 138,
    'title': 'Baseball Ball',
    'price': 8.99,
    'quantity': 2,
    'total': 17.98,
    'discountPercentage': 1.71,
    'discountedTotal': 17.67,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp'}],
  'total': 13037.88,
  'discountedTotal': 11510.81,
  'userId': 1,
  'totalProducts': 4,
  'totalQuantity': 12},
 {'id': 2,
  'products': [{'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 104,
    'title': 'Apple iPhone Charger',
    'price': 19.99,
    'quantity': 2,
    'total': 39.98,
    'discountPercentage': 18.52,
    'discountedTotal': 32.58,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mobile-accessories/apple-iphone-charger/thumbnail.webp'}],
  'total': 139.93,
  'discountedTotal': 125.7,
  'userId': 2,
  'totalProducts': 2,
  'totalQuantity': 7},
 {'id': 3,
  'products': [{'id': 24,
    'title': 'Fish Steak',
    'price': 14.99,
    'quantity': 1,
    'total': 14.99,
    'discountPercentage': 4.23,
    'discountedTotal': 14.36,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/groceries/fish-steak/thumbnail.webp'},
   {'id': 123,
    'title': 'iPhone 13 Pro',
    'price': 1099.99,
    'quantity': 1,
    'total': 1099.99,
    'discountPercentage': 9.37,
    'discountedTotal': 996.92,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp'},
   {'id': 129,
    'title': 'Realme X',
    'price': 299.99,
    'quantity': 1,
    'total': 299.99,
    'discountPercentage': 6.95,
    'discountedTotal': 279.14,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp'},
   {'id': 86,
    'title': 'Man Short Sleeve Shirt',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 6.83,
    'discountedTotal': 93.12,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 2,
    'total': 179.98,
    'discountPercentage': 14.72,
    'discountedTotal': 153.49,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"},
   {'id': 157,
    'title': 'Party Glasses',
    'price': 19.99,
    'quantity': 5,
    'total': 99.94999999999999,
    'discountPercentage': 11.22,
    'discountedTotal': 88.74,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/sunglasses/party-glasses/thumbnail.webp'}],
  'total': 1794.85,
  'discountedTotal': 1625.77,
  'userId': 3,
  'totalProducts': 6,
  'totalQuantity': 15},
 {'id': 4,
  'products': [{'id': 92,
    'title': 'Sports Sneakers Off White Red',
    'price': 109.99,
    'quantity': 3,
    'total': 329.96999999999997,
    'discountPercentage': 0.04,
    'discountedTotal': 329.84,
    'thumbnail': 'https://cdn.dummyjson.com/product-images/mens-shoes/sports-sneakers-off-white-red/thumbnail.webp'},
   {'id': 8,
    'title': "Dior J'adore",
    'price': 89.99,
    'quantity': 4,
    'total': 359.96,
    'discountPercentage': 14.72,
    'discountedTotal': 306.97,
    'thumbnail': "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp"}],
  'total': 689.93,
  'discountedTotal': 636.81,
  'userId': 4,
  'totalProducts': 2,
  'totalQuantity': 7}]

In [24]:
carts = carts['carts']

In [25]:
# normalize at top level
carts_df = pd.json_normalize(carts)
carts_df.head()

,id,products,total,discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12

In [26]:
# rename to avoid confusion later
carts_df = carts_df.rename(columns={
    'id': 'cart_id',
    'total': 'cart_total',
    'discountedTotal': 'cart_discountedTotal'
})

In [27]:
carts_df.head()

,cart_id,products,cart_total,cart_discountedTotal,userId,totalProducts,totalQuantity
0,1,"[{'id': 162, 'title': 'Blue Frock', 'price': 2...",13037.88,11510.81,1,4,12
1,2,"[{'id': 86, 'title': 'Man Short Sleeve Shirt',...",139.93,125.70,2,2,7
2,3,"[{'id': 24, 'title': 'Fish Steak', 'price': 14...",1794.85,1625.77,3,6,15
3,4,"[{'id': 92, 'title': 'Sports Sneakers Off Whit...",689.93,636.81,4,2,7
4,5,"[{'id': 161, 'title': 'Samsung Galaxy Tab Whit...",1467.88,1205.80,5,3,12

In [28]:
# Explode the list of products
carts_exploded = carts_df.explode('products').reset_index(drop=True)
carts_exploded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   cart_id               114 non-null    int64
 1   products              114 non-null    object
 2   cart_total            114 non-null    float64
 3   cart_discountedTotal  114 non-null    float64
 4   userId                114 non-null    int64
 5   totalProducts         114 non-null    int64
 6   totalQuantity         114 non-null    int64
dtypes: float64(2), int64(4), object(1)
memory usage: 6.4+ KB

In [29]:
# Normalize the dictionaries inside the 'products' column
products_df = pd.json_normalize(carts_exploded['products'])

# Add a prefix to specify it's product details
products_df = products_df.add_prefix('prod_')

# join them
carts_final = pd.concat([carts_exploded.drop(columns=['products']), products_df], axis=1)
carts_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   cart_id                  114 non-null    int64
 1   cart_total               114 non-null    float64
 2   cart_discountedTotal     114 non-null    float64
 3   userId                   114 non-null    int64
 4   totalProducts            114 non-null    int64
 5   totalQuantity            114 non-null    int64
 6   prod_id                  114 non-null    int64
 7   prod_title               114 non-null    object
 8   prod_price               114 non-null    float64
 9   prod_quantity            114 non-null    int64
 10  prod_total               114 non-null    float64
 11  prod_discountPercentage  114 non-null    float64
 12  prod_discountedTotal     114 non-null    float64
 13  prod_thumbnail           114 non-null    object
dtypes: float64(6), int64(6), object(2)
memory usage: 12.6+ KB

In [30]:
# create csv
carts_final.to_csv("carts.csv", index=False)
print("Successfully saved as carts.csv")

Successfully saved as carts.csv